# Generated by Django 4.1.1 on 2022-09-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_libro_autor_id_libro_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de pulicación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de pulicación'),
        ),
    ]
