# Generated by Django 4.1.1 on 2022-09-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_autor_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponbile',
            field=models.BooleanField(default=True),
        ),
    ]
